name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with: 
          firstGreeting: "Mary had a little lamb"
          secondGreeting: "With fleece as white as snow"
          thirdGreeting: "Tra-la-la-la-la"
